name: XModAlg
version: "1.18"
license: "GPL-2.0-or-later"
date: 2020-11-17
description: |
    Crossed Modules and Cat1-Algebras

authors:
    - name: Zekeriya Arvasi
      url: mailto:zarvasi@ogu.edu.tr
    - name: Alper Odabas
      url: mailto:aodabas@ogu.edu.tr

maintainers:
    - name: Alper Odabas
      url: mailto:aodabas@ogu.edu.tr

GAP: ">=4.11.0"

needed-pkgs:
    - name: "XMod"
      version: ">=2.82"
      url: "https://gap-packages.github.io/xmod/"
    - name: "LAGUNA"
      version: ">=3.9.3"
      url: "https://gap-packages.github.io/laguna"

www: https://gap-packages.github.io/xmodalg/
readme: README.md
packageinfo: https://gap-packages.github.io/xmodalg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/xmodalg/releases/download/v1.18/XModAlg-1.18.tar.gz

abstract: |
    The <span class="pkgname">XModAlg</span> package provides a collection of functions for computing with crossed modules and cat1-algebras and morphisms of these structures.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    crossed module of algebras, cat1-algebra.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>AO20</span>]   <b class='BibAuthor'>Arvasi, Z. and Odabas, A.</b>,
     <i class='BibTitle'>XModAlg, Crossed Modules and Cat1-Algebras,
             Version 1.18</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/xmodalg/">https://gap-packages.github.io/xmodalg/</a></span>.
    </p>
    

bibtex: |
    @misc{ XModAlg1.18,
      author =           {Arvasi, Z. and Odabas, A.},
      title =            {{XModAlg},    Crossed   Modules   and   Cat1-Algebras,
                          {V}ersion 1.18},
      month =            {Nov},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/xmodalg/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{xmodalg/}}},
      keywords =         {crossed module of algebras; cat1-algebra},
      printedkey =       {AO20}
    }

