name: XModAlg
version: "1.31"
license: "GPL-2.0-or-later"
date: 2025-04-10
description: |
    Crossed Modules and Cat1-Algebras

authors:
    - name: Zekeriya Arvasi
      url: mailto:zarvasi@ogu.edu.tr
    - name: Alper Odabas
      url: mailto:aodabas@ogu.edu.tr

maintainers:
    - name: Alper Odabas
      url: mailto:aodabas@ogu.edu.tr
    - name: Chris Wensley
      url: https://github.com/cdwensley

GAP: ">=4.12.0"

needed-pkgs:
    - name: "XMod"
      version: ">=2.87"
      url: "https://gap-packages.github.io/xmod/"
    - name: "LAGUNA"
      version: ">=3.9.3"
      url: "https://gap-packages.github.io/laguna"

www: https://gap-packages.github.io/xmodalg/
readme: README.md
packageinfo: https://gap-packages.github.io/xmodalg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/xmodalg/releases/download/v1.31/XModAlg-1.31.tar.gz

abstract: |
    The <span class="pkgname">XModAlg</span> package provides a collection of functions for computing with crossed modules and cat1-algebras and morphisms of these structures.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    crossed module of algebras, cat1-algebra.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>AOW25</span>]   <b class='BibAuthor'>Arvasi, Z., Odabas, A. and Wensley, C.</b>,
     <i class='BibTitle'>XModAlg, Crossed Modules and Cat1-Algebras,
             Version 1.31</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/xmodalg/">https://gap-packages.github.io/xmodalg/</a></span>.
    </p>
    

bibtex: |
    @misc{ XModAlg,
      author =           {Arvasi, Z. and Odabas, A. and Wensley, C.},
      title =            {{XModAlg},         {Crossed         Modules        and
                          Cat1\texttt{\symbol{45}}Algebras}, {V}ersion 1.31},
      month =            {Apr},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/xmodalg/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{xmodalg/}}},
      keywords =         {crossed          module          of          algebras;
                          cat1\texttt{\symbol{45}}algebra},
      printedkey =       {AOW25}
    }

